### ISSUE TITLE
Please point out clearly the code required >= python3.9

### ISSUE THREAD

**Issue by Adam-fei** [deepmind/dmvr#2]
Hi, I find out that your code used some feature of python version >= 3.9
Could you please write this in the Readme.md in the example folder?

Thanks :)

**Comment by EherSenaw** [comment]
> Hi, I find out that your code used some feature of python version >= 3.9 Could you please write this in the Readme.md in the example folder?
> 
> Thanks :)

Thanks to @Adam-fei, your comment was helpful for me to deal with using VATT.

**Comment by AlyssaYoung** [comment]
> Hi, I find out that your code used some feature of python version >= 3.9 Could you please write this in the Readme.md in the example folder?
> 
> Thanks :)

Excuse me. I am dealing with another problem which is described in [https://github.com/deepmind/dmvr/issues/1](url) and have no idea . I wonder whether you have encountered the same problem.

**Comment by lsmaira** [comment]
Thanks for filing this bug. Fixed in 7ebb5702e64de1e6a4ca89fc678e6d17f56ff94a
