### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by ericosmic** [deepmind/dmvr#3]
when run generate_from_file.py , happen this error:

![image](https://user-images.githubusercontent.com/35327931/151641592-03a12aba-92e9-4e4c-b7a2-7c3cac5280c1.png)

**Comment by lsmaira** [comment]
Thanks for filing the bug. It should be fixed in commit bdb0cbdc97da735ef98c1e5973bfb93ce727b8c8
